name: .NET Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore ./ISTU_TEST_LR1/ISTU_TEST_LR1.sln

      - name: Build
        run: dotnet build ./ISTU_TEST_LR1/ISTU_TEST_LR1.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test ./ISTU_TEST_LR1/ISTU_TEST_LR1.sln --configuration Release --no-build